### login
POST http://127.0.0.1:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "arifin@lenna.ai",
    "password": "password"
}

### restricted check authentication
GET http://127.0.0.1:3000/api/data HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWZpbkBsZW5uYS5haSIsImV4cCI6MTcxNTA3NDg3M30.wiR6j_Othdsdydbwum6CBYH0r_-5y2en8Q-FGOOENwQ

### get all post
GET http://127.0.0.1:3000/api/post?page=1&page_size=10 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWZpbkBsZW5uYS5haSIsImV4cCI6MTcxNTA3NDg3M30.wiR6j_Othdsdydbwum6CBYH0r_-5y2en8Q-FGOOENwQ

### get post by id
GET http://127.0.0.1:3000/api/post/23 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWZpbkBsZW5uYS5haSIsImV4cCI6MTcxNTA3NDg3M30.wiR6j_Othdsdydbwum6CBYH0r_-5y2en8Q-FGOOENwQ

### create a new post
POST http://127.0.0.1:3000/api/post HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWZpbkBsZW5uYS5haSIsImV4cCI6MTcxNTA3NDg3M30.wiR6j_Othdsdydbwum6CBYH0r_-5y2en8Q-FGOOENwQ

{
    "content": "password 15"
}


### insert a new post2
POST http://127.0.0.1:3000/Post HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="/storage/files/image1.png"
Content-Type: image/png

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

arifin
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

sample@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundary7MA4YWxkTrZu0gW--


